# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "Install Python Requirements"
    command: |
      pip install -r requirements.txt
  
  - name: "Install Ubuntu Packages"
    command: |
      sudo apt update -y
      sudo apt install -y vim wget ip-utils-ping net-tools nc

